Repository owncloud/android, pull requests merged in 2018-10, with the labels that each got.

#2275 String improvements
  res/layout-land/activity_pattern_lock.xml
  res/layout/activity_pattern_lock.xml
  res/layout/fingerprint_dialog.xml
  res/layout/generic_explanation.xml
  res/layout/passcodelock.xml
  res/layout/upload_files_layout.xml
  res/layout/uploader_layout.xml
  res/values/strings.xml
  src/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/com/owncloud/android/ui/activity/FileActivity.java
  src/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  src/com/owncloud/android/ui/dialog/CredentialsDialogFragment.java
  src/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
  src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java
Labels: approved by qa

#2301 Pattern lock bug fixed
  src/com/owncloud/android/authentication/PatternManager.java
  src/com/owncloud/android/ui/activity/PatternLockActivity.java
Labels: approved by qa

#2305 Sorting menu in file picker when uploading.
  res/menu/main_menu.xml
  res/menu/sort_menu.xml
  src/com/owncloud/android/db/PreferenceManager.java
  src/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/com/owncloud/android/ui/adapter/FileListListAdapter.java
  src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java
  src/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  src/com/owncloud/android/utils/FileStorageUtils.java
  src/third_parties/daveKoeller/AlphanumComparator.java
Labels: approved by qa

#2326 Include new steps for 2.9 wizard
  build.gradle
  res/drawable-hdpi/whats_new_av_offline_jobs.png
  res/drawable-hdpi/whats_new_current_folder_search.png
  res/drawable-hdpi/whats_new_select_all.png
  res/drawable-xhdpi/whats_new_av_offline_jobs.png
  res/drawable-xhdpi/whats_new_current_folder_search.png
  res/drawable-xhdpi/whats_new_select_all.png
  res/values/strings.xml
  src/com/owncloud/android/features/FeatureList.java
  src/com/owncloud/android/ui/activity/WhatsNewActivity.java
Labels: approved by qa

#2267 add fdroid aditional styles
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/featureGraphic.jpeg
  fastlane/metadata/android/en-US/images/phoneScreenshots/1.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/2.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/3.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/4.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/5.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/6.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/7.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/8.png
  fastlane/metadata/android/en-US/short_description.txt
Labels: code approved

#2333 Fix Espresso tests to fit new login view
  androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
  androidTest/java/com/owncloud/android/authentication/SAMLAuthenticatorActivityTest.java
  androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
  androidTest/java/com/owncloud/android/utils/AccountsManager.java
Labels: automation, code approved
