Repository owncloud/android, pull requests merged in 2018-05, with the labels that each got.

#2203 Fab snackbar bug
  res/layout/list_fragment.xml
  res/layout/top_progress_bar.xml
  src/com/owncloud/android/ui/activity/FileActivity.java
  src/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  src/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: approved by qa

#2138 add fix for av offline flag gets removed when file gets renamed
  src/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/com/owncloud/android/operations/SynchronizeFolderOperation.java
Labels: approved by qa, code approved

#2157 make oauth request using custom tabs
  AndroidManifest.xml
  build.gradle
  oc_jb_workaround/AndroidManifest.xml
  res/anim/slide_in_left.xml
  res/anim/slide_in_right.xml
  res/anim/slide_out_left.xml
  res/anim/slide_out_right.xml
  res/values/strings.xml
  src/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/com/owncloud/android/authentication/OAuthWebViewClient.java
  src/com/owncloud/android/ui/dialog/LoginWebViewDialog.java
Labels: OAUTH, approved by qa, code approved

#2195 refactor PublicShareDialogFragment
  src/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java
Labels: approved by qa, code approved

#2173 make one pannel for tablets
  res/values-large-land/bools.xml
  res/values/bools.xml
  src/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/com/owncloud/android/ui/preview/PreviewTextFragment.java
Labels: approved by qa, code approved

#2198 Code Putzen 2: refactor PreviewVideoErrorAdapter
  src/com/owncloud/android/ui/preview/PreviewVideoErrorAdapter.java
Labels: approved by qa, code approved

#2191 Code Putzen: refactor ErrorMessageAdapter
  src/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.java
Labels: approved by qa, code approved

#2227 Fix typo contribution
  CONTRIBUTING.md
Labels: approved by qa, code approved

#2200 refactor BitmapUtils
  src/com/owncloud/android/utils/BitmapUtils.java
Labels: approved by qa, code approved

#2199 code cleaning: refactor small bits
  src/com/owncloud/android/ui/SquareImageView.java
  src/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/com/owncloud/android/ui/activity/HookActivity.java
  src/com/owncloud/android/ui/preview/PreviewVideoFragment.java
  src/com/owncloud/android/widgets/ActionEditText.java
Labels: approved by qa, code approved

#2175 fix block for deleted basic/oauth accounts
  res/values/strings.xml
  src/com/owncloud/android/ui/activity/FileActivity.java
  src/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: approved by qa, code approved

#2226 put sort menu into main menu
  build.gradle
  res/menu/main_menu.xml
  res/values/strings.xml
  src/com/owncloud/android/media/MediaService.java
  src/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: approved by qa, code approved

#2152 fix download/available offline icons
  assets/available_offline.svg
  assets/download_pin.svg
  assets/ic_file_download_white_24px.svg
  assets/offline_pin.svg
  assets/uncheck_av.svg
  res/drawable-hdpi/ic_action_download.png
  res/drawable-hdpi/ic_action_set_available_offline.png
  res/drawable-hdpi/ic_action_unset_available_offline.png
  res/drawable-hdpi/ic_available_offline.png
  res/drawable-mdpi/ic_action_download.png
  res/drawable-mdpi/ic_action_set_available_offline.png
  res/drawable-mdpi/ic_action_unset_available_offline.png
  res/drawable-mdpi/ic_available_offline.png
  res/drawable-xhdpi/ic_action_download.png
  res/drawable-xhdpi/ic_action_set_available_offline.png
  res/drawable-xhdpi/ic_action_unset_available_offline.png
  res/drawable-xhdpi/ic_available_offline.png
  res/drawable-xxhdpi/ic_action_download.png
  res/drawable-xxhdpi/ic_action_set_available_offline.png
  res/drawable-xxhdpi/ic_action_unset_available_offline.png
  res/drawable-xxhdpi/ic_available_offline.png
  res/drawable-xxxhdpi/ic_action_download.png
  res/drawable-xxxhdpi/ic_action_set_available_offline.png
  res/drawable-xxxhdpi/ic_action_unset_available_offline.png
  res/drawable/downloaded_pin.png
  res/drawable/error_pin.png
  res/drawable/ic_synced.png
  res/drawable/ic_synchronizing.png
  res/drawable/ic_synchronizing_error.png
  res/drawable/offline_available_pin.png
  res/drawable/sync_pin.png
  res/layout/grid_image.xml
  res/layout/grid_item.xml
  res/layout/list_item.xml
  res/layout/share_file_layout.xml
  res/values/dims.xml
  src/com/owncloud/android/ui/adapter/FileListListAdapter.java
  src/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
Labels: approved by qa, code approved
