Repository owncloud/android, pull requests merged in 2018-12, with the labels that each got.

#2380 Rename root documentation page to index.adoc
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/index.adoc
Labels: documentation, enhancement

#2385 Fix release note links
  docs/modules/ROOT/pages/release_notes.adoc
Labels: documentation

#2307 Sorting options in sharing view
  src/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java
Labels: approved by qa, code approved

#2309 Log in button only enabled when credentials are typed only during basic auth
  src/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: approved by qa, code approved

#2397 Fix espresso tests after merging PR 2302
  androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
Labels: automation

#2395 New resource added for password visibility icon.
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/PublicShareDialogFragment.java
  owncloudApp/src/main/res/drawable-hdpi/ic_hide_black.png
  owncloudApp/src/main/res/drawable-hdpi/ic_view_black.png
  owncloudApp/src/main/res/drawable-mdpi/ic_hide_black.png
  owncloudApp/src/main/res/drawable-mdpi/ic_view_black.png
  owncloudApp/src/main/res/drawable-xhdpi/ic_hide_black.png
  owncloudApp/src/main/res/drawable-xhdpi/ic_view_black.png
  owncloudApp/src/main/res/drawable-xxhdpi/ic_hide_black.png
  owncloudApp/src/main/res/drawable-xxhdpi/ic_view_black.png
  owncloudApp/src/main/res/drawable-xxxhdpi/ic_hide_black.png
  owncloudApp/src/main/res/drawable-xxxhdpi/ic_view_black.png
  owncloudApp/src/main/res/drawable/ic_hide_black.png
  owncloudApp/src/main/res/drawable/ic_view_black.png
Labels: approved by qa, code approved

#2388 Warning to properly set camera folder when enabling camera uploads
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
  owncloudApp/src/main/res/values/strings.xml
Labels: approved by qa, code approved
