Repository owncloud/android, pull requests merged in 2019-04, with the labels that each got.

#2492 Fix and cleanup confirmation dialogs in settings
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
Labels: approved by qa, code approved

#2504 2.0.0 Release Update
  docs/modules/ROOT/assets/images/creating-new-content/select-all-and-inverse-in-uploads-view-small.png
  docs/modules/ROOT/assets/images/creating-new-content/select-all-and-inverse-in-uploads-view.png
  docs/modules/ROOT/assets/images/settings/allow-light-filtering-apps.png
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/release_notes.adoc
  docs/site.yml
Labels: code approved, documentation, enhancement

#2502 Developer menu on version click
  owncloudApp/src/main/java/com/owncloud/android/MainApp.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/FingerprintManager.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/PassCodeManager.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/PatternManager.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
  owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/PatternLockActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Estimation - 3 (M), Sprint, approved by qa, code approved

#2514 Select all and select inverse removed from app bar
  owncloudApp/src/main/res/menu/file_actions_menu.xml
Labels: approved by qa

#2506 [Document provider] Rename File/Folder
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.java
  owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/cursors/RootCursor.java
  owncloudApp/src/main/java/com/owncloud/android/providers/cursors/RootCursor.kt
  owncloudApp/src/main/res/values-v19/bools.xml
  owncloudApp/src/main/res/values/bools.xml
Labels: approved by qa, code approved

#2511 [Document Provider] Delete File/Folder
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.kt
Labels: approved by qa, code approved
