Repository owncloud/android, pull requests merged in 2019-06, with the labels that each got.

#2564 Fix batched permission errors
  owncloudApp/src/main/java/com/owncloud/android/operations/RemoveChunksFolderOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  owncloudApp/src/test/java/com/owncloud/android/utils/ErrorMessageAdapterUnitTest.java
Labels: approved by qa, code approved

#2566 Clear successful / failed uploads bug fix
  owncloudApp/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
Labels: approved by qa, code approved, p2-high

#2559 Fix just created folder dissapears when synchronizing parent folder
  owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
  owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: approved by qa, code approved

#2569 [New architecture] Improve viewmodel behaviour
  owncloudApp/build.gradle
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/ui/FragmentVisibilityIdlingResource.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/ui/usecases/CreatePublicShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/ui/usecases/DeletePublicShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/ui/usecases/EditPublicShareFolderTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/ui/usecases/EditPublicShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/ui/usecases/LoadPublicSharesTest.kt
  owncloudApp/src/main/java/com/owncloud/android/NetworkBoundResource.kt
  owncloudApp/src/main/java/com/owncloud/android/capabilities/repository/OCCapabilityRepository.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/repository/OCShareRepository.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/repository/ShareRepository.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/ui/ShareActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/viewmodel/OCShareViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/vo/Resource.kt
  owncloudApp/src/test/java/com/owncloud/android/NetworkBoundResourceTest.kt
  owncloudApp/src/test/java/com/owncloud/android/shares/repository/OCShareRepositoryTest.kt
  owncloudApp/src/test/java/com/owncloud/android/shares/viewmodel/OCShareViewModelTest.kt
Labels: code approved

#2583 Fix crash when notifying upload result
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: approved by qa, code approved
