Repository owncloud/android, pull requests merged in 2019-02, with the labels that each got.

#2411 remove some lints
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/LogListAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  owncloudApp/src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: approved by qa, code approved, contribution

#2404 Select-all and Select-inverse added to UploadFilesActivity
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FilesUploadHelper.java
  owncloudApp/src/main/res/menu/upload_files_menu.xml
Labels: approved by qa, code approved, contribution, sync::upload

#2438 Android Studio 3.3.1
  build.gradle
Labels: code approved

#2457 make Espresso test at least build
  owncloudApp/build.gradle
  owncloudApp/src/androidTest/AndroidManifest.xml
  owncloudApp/src/androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
  owncloudApp/src/androidTest/java/com/owncloud/android/authentication/SAMLAuthenticatorActivityTest.java
  owncloudApp/src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java
  owncloudApp/src/androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
  owncloudApp/src/androidTest/java/com/owncloud/android/uiautomator/InitialTest.java
Labels: approved by qa, code approved

#2463 Clean up espresso legacy public share tests
  owncloudApp/src/androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
Labels: approved by qa, automation, code approved
