Repository owncloud/android, pull requests merged in 2019-07, with the labels that each got.

#2594 [Espresso] Tests over security section on "Settings"
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/camerauploads/OCSettingsCameraUploadsTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPatternLockTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsSecurityTest.kt
Labels: automation

#2603 [New arch] Private shares: edition and deletion
  owncloudApp/src/androidTest/java/com/owncloud/android/sharees/presentation/ui/SearchShareesFragmentTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/data/OCLocalShareDataSourceTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/data/OCShareDaoTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/domain/privateShares/DeletePrivateShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/domain/privateShares/EditPrivateShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/domain/publicShares/CreatePublicShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/domain/publicShares/DeletePublicShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/domain/publicShares/EditPublicShareFolderTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/domain/publicShares/EditPublicShareTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/presentation/OCShareViewModelTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/presentation/ui/EditPrivateShareFragmentTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/presentation/ui/PublicShareCreationDialogFragmentTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/shares/presentation/ui/TestShareFileActivity.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/utils/Permissions.kt
  owncloudApp/src/main/java/com/owncloud/android/operations/RemoveShareOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/UpdateSharePermissionsOperation.kt
  owncloudApp/src/main/java/com/owncloud/android/operations/common/OperationType.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
  owncloudApp/src/main/java/com/owncloud/android/sharees/presentation/SearchShareesFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/sharees/presentation/UsersAndGroupsSearchProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/data/ShareRepository.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/data/datasources/LocalShareDataSource.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/data/datasources/OCLocalShareDataSource.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/data/datasources/OCRemoteShareDataSource.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/data/datasources/OCShareDao.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/data/datasources/RemoteShareDataSource.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/domain/OCShareRepository.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/OCShareViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/ShareActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/SharePublicLinkListAdapter.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/ShareUserListAdapter.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/EditPrivateShareFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/PublicShareDialogFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/ShareFileFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/ShareFragmentListener.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RemoveShareDialogFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/errorhandling/ErrorMessageAdapter.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/EditShareFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  owncloudApp/src/main/res/layout/edit_share_layout.xml
  owncloudApp/src/test-common/java/com/owncloud/android/utils/TestUtil.kt
  owncloudApp/src/test/java/com/owncloud/android/shares/data/OCRemoteShareDataSourceTest.kt
  owncloudApp/src/test/java/com/owncloud/android/shares/data/OCShareRepositoryTest.kt
  owncloudApp/src/test/java/com/owncloud/android/shares/data/RemoteShareDataSourceTest.kt
Labels: approved by qa, code approved

#2606 Fix glitch when editing folder permissions in public links
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/PublicShareDialogFragment.kt
Labels: approved by qa, code approved

#2609 Update Android documentation for version 2.11
  docs/modules/ROOT/assets/images/android-2.png
  docs/modules/ROOT/assets/images/android-4.png
  docs/modules/ROOT/assets/images/camera/share-from-camera-owncloud-android-app-step-1.png
  docs/modules/ROOT/assets/images/camera/share-from-camera-owncloud-android-app-step-2.png
  docs/modules/ROOT/assets/images/camera/share-from-camera-owncloud-android-app.jpg
  docs/modules/ROOT/assets/images/document-provider-integration/step-1.png
  docs/modules/ROOT/assets/images/document-provider-integration/step-2.png
  docs/modules/ROOT/assets/images/files_folders_view.png
  docs/modules/ROOT/assets/images/logs/show-logs.png
  docs/modules/ROOT/assets/images/release-notes/3923478.png
  docs/modules/ROOT/assets/images/release-notes/3931961.png
  docs/modules/ROOT/assets/images/release-notes/4008946.png
  docs/modules/ROOT/assets/images/release-notes/4008948.png
  docs/modules/ROOT/assets/images/release-notes/4095427.png
  docs/modules/ROOT/assets/images/release-notes/4095432.png
  docs/modules/ROOT/assets/images/release-notes/4181598.png
  docs/modules/ROOT/assets/images/release-notes/4181604.png
  docs/modules/ROOT/assets/images/settings/allow-light-filtering-apps-dialog.png
  docs/modules/ROOT/pages/index.adoc
Labels: documentation, enhancement
