Repository owncloud/android, pull requests merged in 2019-03, with the labels that each got.

#2437 deeper assemble test
  .travis.yml
Labels: Estimation - 1, approved by qa, code approved

#2448 Fix to issue #2422
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: approved by qa, code approved

#2467 fix shell used in makefile
  docs/Makefile
Labels: bug

#2442 remove Lint errors
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/ImageViewCustom.java
  owncloudApp/src/main/java/third_parties/in/srain/cube/GridViewWithHeaderAndFooter.java
  owncloudApp/src/main/res/menu/file_actions_menu.xml
Labels: Estimation - 1 (XS), approved by qa, code approved

#2476 s/DAVdroid/DAVx⁵
  owncloudApp/src/main/res/values/strings.xml
Labels: approved by qa, code approved

#2454 Notch support
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: approved by qa, code approved

#2477 Drawables changed for common error icon
  owncloudApp/src/main/res/drawable-hdpi/common_error_grey.png
  owncloudApp/src/main/res/drawable-mdpi/common_error_grey.png
  owncloudApp/src/main/res/drawable-xhdpi/common_error_grey.png
  owncloudApp/src/main/res/drawable-xxhdpi/common_error_grey.png
  owncloudApp/src/main/res/drawable-xxxhdpi/common_error_grey.png
  owncloudApp/src/main/res/drawable/common_error_grey.png
  owncloudApp/src/main/res/layout/share_public_dialog.xml
  owncloudApp/src/main/res/mipmap-xxxhdpi/ic_home_black.png
Labels: approved by qa

#2490 Fix to crash during creating new folder
  owncloudApp/src/main/res/layout/uploader_layout.xml
Labels: code approved
