Repository owncloud/android, pull requests merged in 2019-05, with the labels that each got.

#2510 [Document Provider] Create Folder
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.kt
Labels: approved by qa, code approved

#2527 [Document Provider] Edit files and save changes
  owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/cursors/FileCursor.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/notifications/NotificationUtils.java
Labels: approved by qa, code approved

#2532 Add TOC Table Of Contents
  docs/modules/ROOT/pages/index.adoc
Labels: documentation, enhancement

#2543 Add code of conduct link to Contributing file
  CONTRIBUTING.md
Labels: documentation

#2538 [Espresso] Settings camera uploads UI tests
  owncloudApp/build.gradle
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/camerauploads/OCSettingsCameraUploadsTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/camerauploads/OCSettingsLocalFolderPickerTest.kt
Labels: code approved

#2528 [Document Provider] Account management
  owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RemoveAccountDialogFragment.java
Labels: approved by qa, code approved

#2545 [Espresso] Settings view: "More" section UI tests
  owncloudApp/build.gradle
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsLogTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsMoreTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsPrivacyPolicyTest.kt
Labels: automation, code approved, settings

#2432 Avoid NPE in RenameFileOperation on IOException
  owncloudApp/src/main/java/com/owncloud/android/operations/RenameFileOperation.java
Labels: Estimation - 1 (XS), Sprint, approved by qa, code approved, contribution

#2537 Release 2.10.1
  CHANGELOG.md
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/db/ProviderMeta.java
  owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: approved by qa

#2479 Changed from custom file picker implementation to SAF
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/LocalFolderPickerActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  owncloudApp/src/main/res/drawable-hdpi/ic_import.png
  owncloudApp/src/main/res/drawable-mdpi/ic_import.png
  owncloudApp/src/main/res/drawable-xhdpi/ic_import.png
  owncloudApp/src/main/res/drawable-xxhdpi/ic_import.png
  owncloudApp/src/main/res/layout/list_fragment.xml
  owncloudApp/src/main/res/layout/upload_files_layout.xml
  owncloudApp/src/main/res/menu/upload_files_menu.xml
Labels: approved by qa
