Repository owncloud/android, pull requests merged in 2019-09, with the labels that each got.

#2650 [Release] 2.12 oem
  owncloudApp/src/main/java/com/owncloud/android/shares/presentation/fragment/ShareFileFragment.kt
Labels: approved by qa

#2646 Include more logs to enhance the way of reproducing some issues
  owncloudApp/src/main/java/com/owncloud/android/AppRater.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/RetryDownloadJobService.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/TransferRequester.java
  owncloudApp/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RateMeDialog.java
Labels: approved by qa, code approved

#2652 Add troubleshooting doc
  TROUBLESHOOTING.md
Labels: code approved, documentation

#2649 Update Antora/Documentation dependencies to the latest versions
  docs/yarn.lock
Labels: code approved, documentation

#2654 Available offline complete information
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  owncloudApp/src/main/res/layout/item_file_list.xml
  owncloudApp/src/main/res/layout/list_item.xml
  owncloudApp/src/main/res/values/dims.xml
Labels: approved by qa, code approved
