Repository owncloud/android, pull requests merged in 2019-11, with the labels that each got.

#2689 remove pointless comments
  owncloudApp/build.gradle
Labels: Estimation - 1 (XS), code approved

#2703 Android Studio 3.5.2
  .idea/codeStyles/Project.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: approved by qa

#2695 remove a pointless layout
  owncloudApp/src/main/res/layout/preference_widget_radiobutton.xml
Labels: Estimation - 1 (XS), Sprint, approved by qa

#2711 Remove e2e legacy tests to be executed with gradlew
  owncloudApp/build.gradle
  owncloudApp/src/androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
  owncloudApp/src/androidTest/java/com/owncloud/android/authentication/SAMLAuthenticatorActivityTest.java
  owncloudApp/src/androidTest/java/com/owncloud/android/ui/activity/PublicShareActivityTest.java
  owncloudApp/src/androidTest/java/com/owncloud/android/uiautomator/InitialTest.java
Labels: Estimation - 1 (XS), Sprint, automation

#2687 Remove the build-artifacts Drone step
  .drone.yml
Labels: documentation

#2710 Sort by date mixing files and folders
  owncloudApp/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FilesUploadHelper.java
  owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: Estimation - 1 (XS), Sprint, approved by qa, code approved

#2721 Ignore "Second Try incorrect" test
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
Labels: Estimation - 1 (XS), automation, code approved

#2713 Splash Screen
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/authentication/FingerprintManager.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/PassCodeManager.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/PatternManager.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
  owncloudApp/src/main/res/drawable-hdpi/splash_image.png
  owncloudApp/src/main/res/drawable/splash_screen.xml
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/styles.xml
Labels: approved by qa, code approved

#2601 Replace the Documentation Makefile with a Shell Script
  .drone.yml
  docs/Makefile
  docs/bin/cli
  docs/books/ownCloud_Android_App_Manual.adoc
  docs/fonts/mplus-1mn-bold.ttf
  docs/fonts/mplus-1mn-medium.ttf
  docs/fonts/mplus-1mn-regular.ttf
  docs/fonts/mplus-1mn-thin.ttf
  docs/fonts/mplus-1p-regular.ttf
  docs/fonts/notoserif-bold_italic.ttf
  docs/resources/themes/owncloud-theme.yml
Labels: automation, documentation, enhancement, p3-medium

#2733 [New arch] Some bug fixing (error handling)
  owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/providers/sharing/UsersAndGroupsSearchProvider.kt
  owncloudApp/src/main/res/values/strings.xml
Labels: Estimation - 2 (S), New architecture, Sprint, code approved

#2679 [Camera Uploads] Sync/Upload for older file, which waits for WiFi too
  owncloudApp/src/main/java/com/owncloud/android/broadcastreceivers/ConnectivityActionReceiver.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/CameraUploadsSyncJobService.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: Estimation - 2 (S), Sprint, approved by qa, sync::camera_uploads

#2719 Sort by size mixing files and folders
  owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: approved by qa, code approved

#2720 [FIX] Fix change device language leads to new image folder name
  owncloudApp/src/main/java/com/owncloud/android/db/PreferenceManager.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  owncloudApp/src/main/res/layout/upload_list_item.xml
  owncloudApp/src/main/res/values-ar/strings.xml
  owncloudApp/src/main/res/values-ca/strings.xml
  owncloudApp/src/main/res/values-cs-rCZ/strings.xml
  owncloudApp/src/main/res/values-da/strings.xml
  owncloudApp/src/main/res/values-de-rDE/strings.xml
  owncloudApp/src/main/res/values-de/strings.xml
  owncloudApp/src/main/res/values-el/strings.xml
  owncloudApp/src/main/res/values-en-rGB/strings.xml
  owncloudApp/src/main/res/values-es-rMX/strings.xml
  owncloudApp/src/main/res/values-es/strings.xml
  owncloudApp/src/main/res/values-fi-rFI/strings.xml
  owncloudApp/src/main/res/values-fr/strings.xml
  owncloudApp/src/main/res/values-gl/strings.xml
  owncloudApp/src/main/res/values-he/strings.xml
  owncloudApp/src/main/res/values-hu-rHU/strings.xml
  owncloudApp/src/main/res/values-id/strings.xml
  owncloudApp/src/main/res/values-it/strings.xml
  owncloudApp/src/main/res/values-ja-rJP/strings.xml
  owncloudApp/src/main/res/values-ko/strings.xml
  owncloudApp/src/main/res/values-lt-rLT/strings.xml
  owncloudApp/src/main/res/values-nb-rNO/strings.xml
  owncloudApp/src/main/res/values-nl/strings.xml
  owncloudApp/src/main/res/values-pl/strings.xml
  owncloudApp/src/main/res/values-pt-rBR/strings.xml
  owncloudApp/src/main/res/values-ru/strings.xml
  owncloudApp/src/main/res/values-sl/strings.xml
  owncloudApp/src/main/res/values-sq/strings.xml
  owncloudApp/src/main/res/values-th-rTH/strings.xml
  owncloudApp/src/main/res/values-tr/strings.xml
  owncloudApp/src/main/res/values-zh-rCN/strings.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Estimation - 3 (M), Sprint, approved by qa, code approved
