Repository owncloud/android, pull requests merged in 2019-12, with the labels that each got.

#2739 Resize cloud image from drawer menu
  owncloudApp/src/main/res/drawable-hdpi/drawer_logo.png
  owncloudApp/src/main/res/drawable-mdpi/drawer_logo.png
  owncloudApp/src/main/res/drawable-xhdpi/drawer_logo.png
  owncloudApp/src/main/res/drawable-xxhdpi/drawer_logo.png
  owncloudApp/src/main/res/drawable-xxxhdpi/drawer_logo.png
  owncloudApp/src/main/res/layout-h620dp/drawer.xml
Labels: approved by qa, code approved

#2740 MainApp logging
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
Labels: code approved

#2737 Adjustments in Settings UI tests to avoid flakyness
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/camerauploads/OCSettingsCameraUploadsTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsLogTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/OCSettingsMoreTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPatternLockTest.kt
Labels: Testing, code approved

#2746 remove twice log
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
Labels: approved by qa, code approved

#2734 Fix overwritten files when copying and moving
  owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  owncloudApp/src/main/java/com/owncloud/android/operations/CopyFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/MoveFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/utils/RemoteFileUtils.kt
Labels: approved by qa, code approved

#2759 Update summary of "Release" issue template
  .github/ISSUE_TEMPLATE/release_template.md
Labels: Estimation - 1 (XS), Sprint
