Repository owncloud/android, pull requests merged in 2020-04, with the labels that each got.

#2814 Gradle verify
  .github/workflows/gradle-wrapper-validation.yml
Labels: p3-medium

#2846 Remove temp and tests folders
  .github/workflows/gradle-wrapper-validation.yml
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/utils/RemoteFileUtils.kt
  temp/abe-all.jar
  temp/backup.ab
  tests/AndroidManifest.xml
  tests/res/drawable-hdpi/ic_launcher.png
  tests/res/drawable-ldpi/ic_launcher.png
  tests/res/drawable-mdpi/ic_launcher.png
  tests/res/drawable-xhdpi/ic_launcher.png
  tests/res/values/strings.xml
  tests/src/com/owncloud/android/test/AccountUtilsTest.java
  tests/src/com/owncloud/android/test/FileContentProviderTest.java
Labels: approved by qa

#2859 Fix npe when rotating folder picker activity
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
Labels: approved by qa, code approved
