Repository owncloud/android, pull requests merged in 2020-06, with the labels that each got.

#2898 Replace Travis status CI for Bitrise
  README.md
Labels: Estimation - 1 (XS), Sprint

#2907 Use Android separator instead of homemade one
  owncloudApp/src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/oauth/OAuthUtils.kt
  owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt
  owncloudApp/src/main/java/com/owncloud/android/datamodel/OCFile.java
  owncloudApp/src/main/java/com/owncloud/android/datamodel/OCUpload.java
  owncloudApp/src/main/java/com/owncloud/android/db/PreferenceManager.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/IndexedForest.java
  owncloudApp/src/main/java/com/owncloud/android/operations/CopyFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/MoveFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/Preferences.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  owncloudApp/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  owncloudApp/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: Estimation - 1 (XS), approved by qa, code approved

#2908 Fix iae in FileDataStorageManager constructor
  owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineHandler.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
  owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: approved by qa, code approved
