Repository owncloud/android, pull requests merged in 2020-01, with the labels that each got.

#2782 Android Studio 3.5.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  owncloudApp/build.gradle
Labels: Estimation - 1 (XS), Sprint, approved by qa

#2779 update Room schema 28
  owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/28.json
Labels: Estimation - 1 (XS), Sprint, approved by qa

#2796 Remove a potential crash
  owncloudApp/src/main/java/com/owncloud/android/services/OperationsService.java
  owncloudApp/src/main/java/com/owncloud/android/services/SyncFolderHandler.java
Labels: Estimation - 1 (XS), Sprint, approved by qa, code approved

#2795 Fix crash when trying to connect to self signed certificate
  owncloudApp/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java
Labels: approved by qa, code approved
