Repository owncloud/android, pull requests merged in 2020-09, with the labels that each got.

#2941 Fix crash when notifying download result
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: approved by qa, code approved

#2948 Fix npe when browsing up
  owncloudApp/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: Estimation - 1 (XS), Sprint, code approved

#2942 Handle migration properly and drop old database tables
  owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt
  owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/32.json
  owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt
  owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java
  owncloudData/src/main/java/com/owncloud/android/data/migrations/Migration_32.kt
Labels: approved by qa, code approved

#2961 Update code style
  .idea/codeStyles/Project.xml
Labels: code approved

#2964 [Docs-only] update dependencies for the documentation
  docs/package.json
  docs/yarn.lock
Labels: documentation

#2969 [Docs] Add FAQ
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/faq.adoc
Labels: documentation

#2973 TROUBLESHOOTING.md ==> troubleshooting.adoc
  TROUBLESHOOTING.md
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/troubleshooting.adoc
Labels: documentation

#2967 Fix remote service exception
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/extensions/ContextExt.kt
  owncloudApp/src/main/java/com/owncloud/android/files/services/AvailableOfflineSyncJobService.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
  owncloudApp/src/main/java/com/owncloud/android/media/MediaService.java
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/ui/notifications/NotificationUtils.java
  owncloudApp/src/main/java/com/owncloud/android/utils/NotificationConstants.kt
  owncloudApp/src/main/java/com/owncloud/android/utils/NotificationUtils.kt
Labels: approved by qa
