Repository owncloud/android, pull requests merged in 2021-09, with the labels that each got.

#3264 Use Koin from mavenCentral()
  build.gradle
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/workers/CameraUploadsWorker.kt
Labels: Estimation - 2 (S)

#3361 [New arch] Passcode activity
  changelog/unreleased/3365
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/authentication/BiometricManager.java
  owncloudApp/src/main/java/com/owncloud/android/authentication/PassCodeManager.java
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeManager.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/BiometricActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModelTest.kt
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt
Labels: Approved by qa

#3381 [Fix] Account removed from "Settings" is not removed from the drawer
  CHANGELOG.md
  changelog/unreleased/3381
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
Labels: Approved by qa

#3386 [FIX] Bump exoplayer from 2.14.2 to 2.15.0
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoErrorAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java
Labels: Approved by qa, Estimation - 2 (S), Sprint, Dependencies

#3380 [FIX] App leads to ANR after removing account if there were too many downloaded files
  CHANGELOG.md
  changelog/unreleased/3380
  changelog/unreleased/3381
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/drawer/DrawerViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
Labels: Approved by qa
