Repository owncloud/android, pull requests merged in 2021-03, with the labels that each got.

#3128 Fix glitch showing lens icon in music player
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.java
Labels: approved by qa

#3116 bump exoplayer to version 2.13.2
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/CustomHttpDataSourceFactory.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java
  owncloudApp/src/main/res/layout/custom_playback_control.xml
  owncloudApp/src/main/res/layout/video_preview.xml
Labels: Estimation - 2 (S), Sprint, approved by qa, p3-medium

#3117 fix scroll jump on share to directory
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java
Labels: approved by qa, code approved

#3151 [DOCS] Android Docs Improvements
  docs/modules/ROOT/pages/faq.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/troubleshooting.adoc
Labels: documentation

#3162 add the android.permission.REQUEST_INSTALL_PACKAGES permission
  owncloudApp/src/main/AndroidManifest.xml
Labels: approved by qa

#3179 Bump mockk version to 1.11.0
  build.gradle
  owncloudData/build.gradle
  owncloudDomain/build.gradle
Labels: dependencies

#3177 Do not show sync option in audio preview.
  CHANGELOG.md
  changelog/unreleased/3162
  changelog/unreleased/3177
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.java
Labels: approved by qa
