Repository owncloud/android, pull requests merged in 2021-04, with the labels that each got.

#3186 Remove wizard steps for 2.17
  owncloudApp/src/main/java/com/owncloud/android/features/FeatureList.java
  owncloudApp/src/main/res/drawable/whats_new_avatar_toolbar.png
  owncloudApp/src/main/res/values-gl/strings.xml
  owncloudApp/src/main/res/values-pt-rBR/strings.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Estimation - 1 (XS)

#3190 Glide update
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
Labels: Estimation - 1 (XS), approved by qa

#3182 improve music player design
  CHANGELOG.md
  changelog/unreleased/3121
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.java
  owncloudApp/src/main/res/drawable/ic_place_holder_music_cover_art.xml
  owncloudApp/src/main/res/drawable/ic_place_holder_music_cover_art_overlay.xml
  owncloudApp/src/main/res/layout/preview_audio_fragment.xml
Labels: approved by qa

#3194 update fdroid badge url
  README.md
Labels: Estimation - 1 (XS)

#3200 Show new CI badges on README file
  README.md
Labels: Estimation - 1 (XS)

#3203 Replace kotlin android extensions
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/sharing/SharePublicLinkListAdapter.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/common/BottomSheetFragmentItemView.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortBottomSheetFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortOptionsView.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortType.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/EditPrivateShareFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/PublicShareDialogFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/SearchShareesFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/sharing/fragments/ShareFileFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileListOption.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  owncloudApp/src/main/res/layout/activity_main.xml
  owncloudDomain/build.gradle
  owncloudDomain/src/main/java/com/owncloud/android/domain/sharing/shares/model/OCShare.kt
  owncloudTestUtil/build.gradle
Labels: approved by qa

#3212 Bump room and exoplayer dependencies
  build.gradle
  owncloudApp/build.gradle
Labels: code approved

#3210 [FIX] Snackbar in passcode view is not displayed
  CHANGELOG.md
  changelog/unreleased/3210
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/OCSettingsPasscodeTest.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  owncloudApp/src/main/res/layout/passcodelock.xml
Labels: approved by qa, code approved
