Repository owncloud/android, pull requests merged in 2021-05, with the labels that each got.

#3221 [Feature] Error handling for pattern lock
  changelog/unreleased/3221
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/PatternLockActivity.java
  owncloudApp/src/main/res/layout-land/activity_pattern_lock.xml
  owncloudApp/src/main/res/layout/activity_pattern_lock.xml
Labels: approved by qa, code approved

#3224 [Feature] Use new extensions in the whole project
  owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/RateMeDialog.java
Labels: approved by qa, code approved

#3230 [Feature] Hide biometrical if device does not support it
  CHANGELOG.md
  changelog/unreleased/3230
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt
  owncloudApp/src/main/res/values-ar/strings.xml
  owncloudApp/src/main/res/values-bg-rBG/strings.xml
  owncloudApp/src/main/res/values-ca/strings.xml
  owncloudApp/src/main/res/values-cs-rCZ/strings.xml
  owncloudApp/src/main/res/values-de-rCH/strings.xml
  owncloudApp/src/main/res/values-de-rDE/strings.xml
  owncloudApp/src/main/res/values-de/strings.xml
  owncloudApp/src/main/res/values-en-rGB/strings.xml
  owncloudApp/src/main/res/values-es-rAR/strings.xml
  owncloudApp/src/main/res/values-es-rMX/strings.xml
  owncloudApp/src/main/res/values-es/strings.xml
  owncloudApp/src/main/res/values-eu/strings.xml
  owncloudApp/src/main/res/values-gl/strings.xml
  owncloudApp/src/main/res/values-he/strings.xml
  owncloudApp/src/main/res/values-id/strings.xml
  owncloudApp/src/main/res/values-it/strings.xml
  owncloudApp/src/main/res/values-nb-rNO/strings.xml
  owncloudApp/src/main/res/values-nl/strings.xml
  owncloudApp/src/main/res/values-pl/strings.xml
  owncloudApp/src/main/res/values-pt-rBR/strings.xml
  owncloudApp/src/main/res/values-ru/strings.xml
  owncloudApp/src/main/res/values-sq/strings.xml
  owncloudApp/src/main/res/values-th-rTH/strings.xml
  owncloudApp/src/main/res/values-tr/strings.xml
  owncloudApp/src/main/res/values-zh-rTW/strings.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: approved by qa, code approved

#3240 Fix crash when sharing with ownCloud
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: approved by qa

#3250 Replace mappers with kotlin extensions
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/LocalDataSourceModule.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt
  owncloudData/src/androidTest/java/com/owncloud/android/data/capabilities/db/OCCapabilityDaoTest.kt
  owncloudData/src/androidTest/java/com/owncloud/android/data/sharing/shares/db/OCShareDaoTest.kt
  owncloudData/src/androidTest/java/com/owncloud/android/data/user/UserDaoTest.kt
  owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/implementation/OCLocalCapabilitiesDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/mapper/OCCapabilityMapper.kt
  owncloudData/src/main/java/com/owncloud/android/data/capabilities/db/OCCapabilityDao.kt
  owncloudData/src/main/java/com/owncloud/android/data/sharing/shares/datasources/implementation/OCLocalShareDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/sharing/shares/datasources/mapper/OCShareMapper.kt
  owncloudData/src/main/java/com/owncloud/android/data/user/datasources/implementation/OCLocalUserDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/user/datasources/mapper/UserQuotaMapper.kt
  owncloudData/src/test/java/com/owncloud/android/data/capabilities/datasources/OCLocalCapabilitiesDataSourceTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/capabilities/datasources/mapper/OCCapabilityMapperTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/shares/datasources/OCLocalShareDataSourceTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/shares/datasources/mapper/OCShareMapperTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/user/datasources/OCLocalUserDataSourceTest.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/mappers/Mapper.kt
Labels: Estimation - 1 (XS)
