Repository owncloud/android, pull requests merged in 2022-08, with the labels that each got.

#3725 [FIX] [New arch] Crash when removing account
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/transfers/TransfersViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
Labels: Approved by qa

#3719 [New arch] Fix bottom navigation shortcuts
  owncloudApp/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.kt
  owncloudApp/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/extensions/FragmentExt.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/adapters/filelist/FileListAdapter.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/diffutils/FileListDiffCallback.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortOptionsView.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/SortType.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/filelist/MainFileListViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadPathActivity.java
  owncloudApp/src/main/res/layout/item_file_list.xml
  owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
  owncloudDomain/build.gradle
  owncloudDomain/src/main/java/com/owncloud/android/domain/availableoffline/usecases/GetFilesAvailableOfflineFromAccountAsStreamUseCase.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/DisableThumbnailsForFileUseCase.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetFolderContentAsStreamUseCase.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/GetSharedByLinkForAccountAsStreamUseCase.kt
  owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetFilesSharedByLinkUseCaseTest.kt
  owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetSharedByLinkForAccountAsStreamUseCaseTest.kt
Labels: Estimation - 5 (L), Sprint

#3727 [New Arch] Allow local removal when device is not connected
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/files/operations/FileOperationsViewModel.kt
Labels: Approved by qa, Estimation - 2 (S), Sprint
