Repository owncloud/android, pull requests merged in 2022-04, with the labels that each got.

#3592 [Bugfix] Lock displays shown again
  CHANGELOG.md
  changelog/unreleased/3592
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
Labels: Approved by qa

#3595 [MDM] Lock delay configuration
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/MdmProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
  owncloudApp/src/main/res/values/strings__not_to_translate.xml
  owncloudApp/src/main/res/xml/managed_configurations.xml
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt
Labels: Approved by qa

#3512 Api 31
  build.gradle
  owncloudApp/build.gradle
  owncloudApp/src/debug/java/com/owncloud/android/utils/DebugInjector.kt
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  owncloudApp/src/main/java/com/owncloud/android/files/services/FileUploader.java
  owncloudApp/src/main/java/com/owncloud/android/media/MediaService.java
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/authentication/LoginActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/utils/NotificationUtils.kt
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#3594 [FEATURE] Release Notes
  .github/ISSUE_TEMPLATE/release_template.md
  CHANGELOG.md
  changelog/unreleased/3594
  changelog/unreleased/3616
  owncloudApp/build.gradle
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/SettingsFragmentTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/ui/activity/ReleaseNotesActivityTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/utils/ReleaseNotesList.kt
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/features/FeatureList.java
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/releasenotes/ReleaseNote.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/releasenotes/ReleaseNotesActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ReleaseNotesAdapter.kt
  owncloudApp/src/main/res/drawable/ic_release_notes_architecture.xml
  owncloudApp/src/main/res/drawable/ic_release_notes_autorenew.xml
  owncloudApp/src/main/res/drawable/ic_release_notes_healing.xml
  owncloudApp/src/main/res/drawable/ic_settings_whats_new.xml
  owncloudApp/src/main/res/layout/release_notes_activity.xml
  owncloudApp/src/main/res/layout/release_notes_item.xml
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/strings.xml
  owncloudApp/src/main/res/xml/settings.xml
Labels: Approved by qa

#3624 [FEATURE] Support for hidden files
  CHANGELOG.md
  changelog/unreleased/3624
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/advanced/SettingsAdvancedFragmentTest.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/SettingsActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsAdvancedFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsAdvancedViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
  owncloudApp/src/main/res/values/strings.xml
  owncloudApp/src/main/res/xml/settings.xml
  owncloudApp/src/main/res/xml/settings_advanced.xml
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsAdvancedViewModelTest.kt
Labels: Approved by qa

#3582 [New Design] Passcode Screen
  changelog/unreleased/3569
  changelog/unreleased/3582
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/PassCodeActivityTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/security/SettingsSecurityFragmentTest.kt
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/BiometricActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/BiometricManager.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/PassCodeActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/NumberKeyboard.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/NumberKeyboardListener.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/PassCodeActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/PassCodeManager.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/PasscodeAction.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/PasscodeType.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/SquareFrameLayout.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/security/passcode/Status.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsSecurityFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/security/BiometricViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java
  owncloudApp/src/main/res/drawable/ic_fingerprint.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_ic_backspace.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_ic_backspace_normal.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_ic_backspace_pressed.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_ic_fingerprint.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_ic_fingerprint_normal.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_ic_fingerprint_pressed.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_key_bg.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_key_bg_normal.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_key_bg_pressed.xml
  owncloudApp/src/main/res/drawable/numberkeyboard_key_text_color.xml
  owncloudApp/src/main/res/layout-w600dp/passcodelock.xml
  owncloudApp/src/main/res/layout/numberkeyboard_layout.xml
  owncloudApp/src/main/res/layout/ssl_untrusted_cert_layout.xml
  owncloudApp/src/main/res/layout/ssl_validator_layout.xml
  owncloudApp/src/main/res/values-h640dp/dims.xml
  owncloudApp/src/main/res/values-h740dp/dims.xml
  owncloudApp/src/main/res/values/attrs.xml
  owncloudApp/src/main/res/values/dims.xml
  owncloudApp/src/main/res/values/strings.xml
  owncloudApp/src/main/res/values/styles.xml
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/security/BiometricViewModelTest.kt
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/security/PassCodeViewModelTest.kt
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsSecurityViewModelTest.kt
Labels: Approved by qa

#3615 [FEATURE] Prevent taking screenshots
  CHANGELOG.md
  changelog/unreleased/3615
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/res/values/setup.xml
Labels: Approved by qa

#3636 Share text when using public share includes username instead of the full name
  CHANGELOG.md
  changelog/unreleased/3636
  owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: Approved by qa

#3515 Bump Exoplayer
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PrepareVideoPlayerAsyncTask.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java
Labels: Approved by qa, Estimation - 2 (S)

#3593 Replace livedata with stateflow in camera uploads screens
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsPictureUploadsFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/ui/settings/fragments/SettingsVideoUploadsFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsPictureUploadsViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/viewmodels/settings/SettingsVideoUploadsViewModel.kt
Labels: Approved by qa, Estimation - 3 (M)
