Repository owncloud/android, pull requests merged in 2023-04, with the labels that each got.

#3997 [SPACES] WebDAV permissions in files
  owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
  owncloudApp/src/main/java/com/owncloud/android/files/FileMenuFilter.java
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java
  owncloudApp/src/main/res/menu/file_actions_menu.xml
  owncloudApp/src/main/res/values/strings.xml
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCFile.kt
Labels: Approved by qa

#4003 [Release] 4.0 beta.2
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4001 Add monochrome icon
  owncloudApp/src/main/res/mipmap-anydpi-v26/icon.xml
Labels: Approved by qa, Estimation - 1 (XS)

#4011 Add prompt to the authentication flow
  CHANGELOG.md
  changelog/unreleased/4011
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/oauth/OAuthUtils.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/strings__not_to_translate.xml
  owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt
Labels: Approved by qa

#4018 Add consent to default prompt value
  owncloudApp/src/main/res/values/setup.xml
Labels: Estimation - 1 (XS)

#4026 [FIX] Incorrect list of av. offline files in shortcut when browsing from Details
  CHANGELOG.md
  changelog/unreleased/4026
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
Labels: Approved by qa
