Repository owncloud/android, pull requests merged in 2023-10, with the labels that each got.

#3966 Koin dsl
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/LocalDataSourceModule.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RemoteDataSourceModule.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/RepositoryModule.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
Labels: Estimation - 2 (S), Sprint

#4160 [FEATURE REQUEST] OCIS: "Share to" allows only upload to personal "space"
  CHANGELOG.md
  changelog/unreleased/4160
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/spaces/SpacesListViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/ReceiveExternalFilesViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.java
  owncloudApp/src/main/res/layout/uploader_layout.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4185 Add missing calens reports
  CHANGELOG.md
  changelog/unreleased/3966
  changelog/unreleased/4179
  changelog/unreleased/4183
Labels: Technical

#4186 Update some files after removing submodule
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/release_template.md
  SETUP.md
Labels: Documentation

#4182 language review
  owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/PublicShareCreationDialogFragmentTest.kt
  owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/ShareFileFragmentTest.kt
  owncloudApp/src/main/res/values/strings.xml
Labels: UI / UX, Estimation - 2 (S), Sprint

#4177 Migrate to media3
  gradle/libs.versions.toml
  owncloudApp/build.gradle
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/CustomHttpDataSourceFactory.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PrepareVideoPlayerAsyncTask.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoErrorAdapter.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFragment.java
  owncloudApp/src/main/res/layout/custom_playback_control.xml
  owncloudApp/src/main/res/layout/video_layout.xml
  owncloudApp/src/main/res/layout/video_preview.xml
  owncloudApp/src/main/res/values/styles.xml
Labels: Approved by qa

#4196 Release template: add rebase-merge option in rebase against stable to…
  .github/ISSUE_TEMPLATE/release_template.md
Labels: Technical

#4191 [FEATURE REQUEST] Manage deep links and open the app correctly
  CHANGELOG.md
  changelog/unreleased/4191
  owncloudApp/src/main/AndroidManifest.xml
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/ViewModelModule.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AuthenticationViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperationsViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/strings.xml
  owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/DeepLinkException.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/ManageDeepLinkUseCase.kt
Labels: Approved by qa
