Repository owncloud/android, pull requests merged in 2023-09, with the labels that each got.

#4135 Replace runBlocking with runTest for testing
  owncloudData/build.gradle
  owncloudData/src/test/java/com/owncloud/android/data/appRegistry/datasources/implementation/OCLocalAppRegistryDataSourceTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCLocalFileDataSourceTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/file/repository/OCFileRepositoryTest.kt
  owncloudDomain/src/test/java/com/owncloud/android/domain/files/usecases/GetFileWithSyncInfoByIdUseCaseTest.kt
Labels: Estimation - 2 (S), Sprint

#4138 [FEATURE REQUEST] "Apply to all" when many name conflicts arise
  CHANGELOG.md
  changelog/unreleased/4138
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperationsViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/dialog/FileAlreadyExistsDialog.kt
  owncloudApp/src/main/res/layout/dialog_file_already_exists.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4144 More improvements in release checklist
  .github/ISSUE_TEMPLATE/release_template.md
Labels: Estimation - 1 (XS), Sprint
