Repository owncloud/android, pull requests merged in 2023-05, with the labels that each got.

#4021 updated the findViewById to use view binding
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
Labels: Estimation - 2 (S)

#4030 Add prefix "technical" to Calens
  .github/workflows/calens.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: Technical

#4032 [FEATURE REQUEST] Add suggested app to access document provider
  CHANGELOG.md
  changelog/unreleased/4032
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/SettingsMoreFragmentTest.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/settings/more/SettingsMoreFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/settings/more/SettingsMoreViewModel.kt
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/strings.xml
  owncloudApp/src/main/res/xml/settings_more.xml
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsMoreViewModelTest.kt
Labels: Approved by qa

#4038 [FIX] Make ShareActivity not-exported
  CHANGELOG.md
  changelog/unreleased/4038
  owncloudApp/src/main/AndroidManifest.xml
Labels: Security

#4040 [FEATURE REQUEST] File name conflict starting by (1)
  CHANGELOG.md
  changelog/unreleased/4040
  owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCRemoteFileDataSource.kt
  owncloudData/src/test/java/com/owncloud/android/data/file/datasources/OCRemoteFileDataSourceTest.kt
Labels: Approved by qa
