Repository owncloud/android, pull requests merged in 2023-12, with the labels that each got.

#4212 [FEATURE REQUEST] Select correct user and navigate to the correct file when opening via deep link
  CHANGELOG.md
  changelog/unreleased/4212
  owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/MainFileListFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/operations/FileOperationsViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/res/values/strings.xml
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/properties/OCFileId.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/properties/OCMetaPathForUser.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/webdav/properties/OCSpaceId.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/GetRemoteMetaFileOperation.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoteMetaFile.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/FileService.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/services/implementation/OCFileService.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/spaces/GetRemoteSpacesOperation.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/datasources/RemoteFileDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCRemoteFileDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
  owncloudData/src/test/java/com/owncloud/android/data/files/datasources/implementation/OCRemoteFileDataSourceTest.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/model/OCMetaFile.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/ManageDeepLinkUseCase.kt
  owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCFile.kt
Labels: Approved by qa

#4247 [RELEASE ] 4.2.0-beta.1
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4255 Add some fixes to release notes 4.2.0
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/res/values-de-rDE/strings.xml
  owncloudApp/src/main/res/values-de/strings.xml
  owncloudApp/src/main/res/values-en-rGB/strings.xml
  owncloudApp/src/main/res/values-et-rEE/strings.xml
  owncloudApp/src/main/res/values-sq/strings.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Technical, Estimation - 1 (XS)

#4257 [FEATURE REQUEST] Don't redact auth type HTTP request logging
  CHANGELOG.md
  changelog/unreleased/4257
  owncloudApp/src/main/java/com/owncloud/android/MainApp.kt
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/CommonModule.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/LogsProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/strings__not_to_translate.xml
  owncloudApp/src/main/res/xml/managed_configurations.xml
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/logging/LogInterceptor.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/OCFileLoggingTree.kt
Labels: Approved by qa

#4256 [BUG] Thumbnails glitches if there are many files in the folder
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/filelist/FileListAdapter.kt
  owncloudApp/src/main/res/layout/grid_item.xml
  owncloudApp/src/main/res/values/dims.xml
Labels: Approved by qa

#4260 [FIX] Add "scope" parameter to /token endpoint HTTP requests
  CHANGELOG.md
  changelog/unreleased/4260
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AccountAuthenticator.java
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/oauth/params/TokenRequestParams.kt
  owncloudData/src/main/java/com/owncloud/android/data/oauth/datasources/implementation/OCRemoteOAuthDataSource.kt
  owncloudData/src/test/java/com/owncloud/android/data/oauth/RemoteOAuthUtils.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/TokenRequest.kt
  owncloudTestUtil/src/main/java/com/owncloud/android/testutil/oauth/TokenRequest.kt
Labels: Estimation - 2 (S)

#4266 [FIX] Unify http log
  CHANGELOG.md
  changelog/unreleased/4266
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpConstants.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/logging/LogBuilder.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/logging/LogInterceptor.kt
Labels: Approved by qa
