Repository owncloud/android, pull requests merged in 2024-01, with the labels that each got.

#4263 Handle audio focus and becoming noisy
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
Labels: Approved by qa, Estimation - 2 (S)

#4270 [FEATURE REQUEST] Block UI when deleting files
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
Labels: Approved by qa

#4283 [TECHNICAL] Improve biometrical authentication security
  CHANGELOG.md
  changelog/unreleased/4283
  owncloudApp/src/main/java/com/owncloud/android/presentation/security/biometric/BiometricActivity.kt
Labels: Approved by qa

#4265 [FIX] Some bugs related to Details view
  CHANGELOG.md
  changelog/unreleased/4265
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
Labels: Approved by qa

#4280 [BUG] Some bugs in log files downloads
  CHANGELOG.md
  changelog/unreleased/4205
  owncloudApp/src/main/java/com/owncloud/android/presentation/logging/LogsListActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/logging/RecyclerViewLogsAdapter.kt
Labels: Approved by qa

#4276 [FEATURE REQUEST] Manage password policy in live mode
  CHANGELOG.md
  changelog/unreleased/4276
  owncloudApp/src/androidTest/java/com/owncloud/android/sharing/shares/ui/PublicShareCreationDialogFragmentTest.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/sharing/shares/PublicShareDialogFragment.kt
  owncloudApp/src/main/res/drawable/ic_check_password_policy.xml
  owncloudApp/src/main/res/drawable/ic_cross_warning_password_policy.xml
  owncloudApp/src/main/res/layout/share_public_dialog.xml
  owncloudApp/src/main/res/values/strings.xml
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/RemoteCapability.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/responses/CapabilityResponse.kt
  owncloudData/schemas/com.owncloud.android.data.OwncloudDatabase/44.json
  owncloudData/src/main/java/com/owncloud/android/data/OwncloudDatabase.kt
  owncloudData/src/main/java/com/owncloud/android/data/ProviderMeta.java
  owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/implementation/OCLocalCapabilitiesDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/capabilities/datasources/mapper/RemoteCapabilityMapper.kt
  owncloudData/src/main/java/com/owncloud/android/data/capabilities/db/OCCapabilityEntity.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/capabilities/model/OCCapability.kt
  owncloudTestUtil/src/main/java/com/owncloud/android/testutil/OCCapability.kt
Labels: Approved by qa

#4277 Alert Dialog title color issue in Samsung devices
  changelog/unreleased/4277
  owncloudApp/src/main/res/layout/share_public_dialog.xml
Labels: Approved by qa

#4291 [FEATURE REQUEST] [OIDC] Branding option to remove `login_hint` and `user` parameter from re-login URL
  CHANGELOG.md
  changelog/unreleased/4291
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/oauth/OAuthUtils.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/SplashActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/utils/MdmConfigurations.kt
  owncloudApp/src/main/res/values/setup.xml
  owncloudApp/src/main/res/values/strings__not_to_translate.xml
  owncloudApp/src/main/res/xml/managed_configurations.xml
  owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt
Labels: Approved by qa

#4287 [BUG] 4.1.1 composes /app/list path wrong when instance is installed in subfolder (/owncloud)
  CHANGELOG.md
  changelog/unreleased/4287
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/appregistry/GetRemoteAppRegistryOperation.kt
Labels: Approved by qa

#4295 [BUG] Invalid copy into descendant in different spaces
  CHANGELOG.md
  changelog/unreleased/4295
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/usecases/CopyFileUseCase.kt
Labels: Approved by qa

#4298 Added comment explaining the purposes of Cipher object in biometrics
  owncloudApp/src/main/java/com/owncloud/android/presentation/security/biometric/BiometricViewModel.kt
Labels: Estimation - 1 (XS)

#4285 Handle error 423 (locked file)
  changelog/unreleased/4285
  owncloudApp/src/main/java/com/owncloud/android/extensions/ThrowableExt.kt
  owncloudApp/src/main/res/values/strings.xml
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
  owncloudData/src/main/java/com/owncloud/android/data/RemoteOperationHandler.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/exceptions/ResourceLockedException.kt
Labels: Approved by qa

#4296 [FIX] Hardcoded name in logs leads to crash
  CHANGELOG.md
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/OCFileLoggingTree.kt
Labels: Bug, Approved by qa, Estimation - 2 (S)
