Repository owncloud/android, pull requests merged in 2024-03, with the labels that each got.

#4320 [FEATURE REQUEST] Automatic removal of downloaded files and local storage clean up
  CHANGELOG.md
  changelog/unreleased/4320
  owncloudApp/src/main/java/com/owncloud/android/dependecyinjection/UseCaseModule.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/settings/advanced/AdvancedSettingsUtils.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/settings/advanced/SettingsAdvancedFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/settings/advanced/SettingsAdvancedViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/providers/WorkManagerProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewAudioFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  owncloudApp/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/usecases/files/RemoveLocallyFilesWithLastUsageOlderThanGivenTimeUseCase.kt
  owncloudApp/src/main/java/com/owncloud/android/workers/RemoveLocallyFilesWithLastUsageOlderThanGivenTimeWorker.kt
  owncloudApp/src/main/res/values-de-rDE/strings.xml
  owncloudApp/src/main/res/values-de/strings.xml
  owncloudApp/src/main/res/values-en-rGB/strings.xml
  owncloudApp/src/main/res/values-et-rEE/strings.xml
  owncloudApp/src/main/res/values-pt-rBR/strings.xml
  owncloudApp/src/main/res/values-sq/strings.xml
  owncloudApp/src/main/res/values/strings.xml
  owncloudApp/src/main/res/xml/settings_advanced.xml
  owncloudApp/src/test/java/com/owncloud/android/presentation/viewmodels/settings/SettingsAdvancedViewModelTest.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/datasources/LocalFileDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/db/FileDao.kt
  owncloudData/src/main/java/com/owncloud/android/data/files/repository/OCFileRepository.kt
  owncloudData/src/test/java/com/owncloud/android/data/files/datasources/implementation/OCLocalFileDataSourceTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/files/repository/OCFileRepositoryTest.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/files/FileRepository.kt
Labels: Approved by qa

#4325 [FEATURE REQUEST] Make automatic discovery of the account
  CHANGELOG.md
  changelog/unreleased/4325
  owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementAdapter.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/workers/AccountDiscoveryWorker.kt
  owncloudApp/src/main/res/layout/account_item.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4330 [FEATURE REQUEST] Improvements in "Manage accounts" view
  CHANGELOG.md
  changelog/unreleased/4330
  owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/accounts/AccountsManagementAdapter.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  owncloudApp/src/main/res/layout/account_item.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4339 [FIX] Lens icon in folder picker
  CHANGELOG.md
  changelog/unreleased/4339
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4346 Modify commit messages in calens and dependabot to fit "Conventional commits"
  .github/dependabot.yml
  .github/workflows/calens.yml
  CHANGELOG.md
  changelog/unreleased/4346
Labels: Technical, Estimation - 1 (XS)

#4347 Add conventional commits to CONTRIBUTING.md file in order to be understood by community
  CONTRIBUTING.md
Labels: Documentation, Estimation - 1 (XS)
