Repository owncloud/android, pull requests merged in 2025-07, with the labels that each got.

#4621 [FEATURE REQUEST] Modify sbom workflow to push to the repo
  .github/workflows/sbom.yml
  CHANGELOG.md
  changelog/unreleased/4599
Labels: Estimation - 2 (S), Sprint

#4636 [FIX] Push sbom into master after merging via ssh
  .github/workflows/sbom.yml
Labels: Estimation - 2 (S), GitHub Actions

#4639 [FIX] Change predefined step that used https for another with commands
  .github/workflows/sbom.yml
Labels: Estimation - 1 (XS), GitHub Actions

#4632 [FEATURE REQUEST] Create new set of configurations for Kiteworks servers in setup.xml
  CHANGELOG.md
  changelog/unreleased/4632
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/AccountAuthenticator.java
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/LoginActivity.kt
  owncloudApp/src/main/java/com/owncloud/android/presentation/authentication/oauth/OAuthUtils.kt
  owncloudApp/src/main/res/values/setup.xml
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/ConnectionValidator.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudAccount.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SingleSessionManager.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java
  owncloudData/src/main/java/com/owncloud/android/data/authentication/AuthenticationConstants.kt
  owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCLocalAuthenticationDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/authentication/datasources/implementation/OCRemoteAuthenticationDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/oauth/datasources/implementation/OCRemoteOAuthDataSource.kt
  owncloudData/src/main/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSource.kt
  owncloudData/src/test/java/com/owncloud/android/data/oauth/datasources/implementation/OCRemoteOAuthDataSourceTest.kt
  owncloudData/src/test/java/com/owncloud/android/data/server/datasources/implementation/OCRemoteServerInfoDataSourceTest.kt
  owncloudDomain/src/main/java/com/owncloud/android/domain/authentication/oauth/model/OIDCServerConfiguration.kt
  owncloudTestUtil/src/main/java/com/owncloud/android/testutil/oauth/OIDCServerConfiguration.kt
Labels: Approved by qa

#4645 [TECHNICAL] Remove 4.6.0 release notes
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/res/values-de/strings.xml
  owncloudApp/src/main/res/values-es/strings.xml
  owncloudApp/src/main/res/values-et-rEE/strings.xml
  owncloudApp/src/main/res/values-pt-rBR/strings.xml
  owncloudApp/src/main/res/values-sq/strings.xml
  owncloudApp/src/main/res/values-tr/strings.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Technical

#4652 [FIX] Crash in TransferListFragment (Play Console)
  CHANGELOG.md
  changelog/unreleased/4652
  owncloudApp/src/main/java/com/owncloud/android/presentation/transfers/TransferListFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
Labels: Approved by qa

#4654 [FIX] Re-login not working properly when credentials expire
  CHANGELOG.md
  changelog/unreleased/4654
  owncloudApp/src/main/java/com/owncloud/android/presentation/files/details/FileDetailsFragment.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
Labels: Authentication, Approved by qa
