Repository owncloud/android, pull requests merged in 2025-08, with the labels that each got.

#4657 [FIX] Removed files in failed uploads
  CHANGELOG.md
  changelog/unreleased/4657
  owncloudApp/src/main/java/com/owncloud/android/providers/FileContentProvider.kt
  owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/RetryUploadFromSystemUseCase.kt
  owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFileFromSystemUseCase.kt
  owncloudApp/src/main/java/com/owncloud/android/usecases/transfers/uploads/UploadFilesFromSystemUseCase.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/chunks/ChunkedUploadFromFileSystemOperation.kt
Labels: Approved by qa

#4660 [RELEASE] 4.6.2
  CHANGELOG.md
  changelog/4.6.2_2025-08-13/4657
  owncloudApp/build.gradle
Labels: Approved by qa

#4663 [TECHNICAL] Add workflow to test upgrade from "latest" to current
  .github/workflows/update.yml
  CHANGELOG.md
  README.md
  changelog/unreleased/4663
Labels: Technical, GitHub Actions

#4669 [TECHNICAL] Remove 4.6 release notes
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
  owncloudApp/src/main/res/values-de/strings.xml
  owncloudApp/src/main/res/values-es/strings.xml
  owncloudApp/src/main/res/values-et-rEE/strings.xml
  owncloudApp/src/main/res/values-pt-rBR/strings.xml
  owncloudApp/src/main/res/values-sq/strings.xml
  owncloudApp/src/main/res/values-tr/strings.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Technical
