Repository owncloud/android, pull requests merged in 2025-02, with the labels that each got.

#4543 [TECHNICAL] Send just one Detekt command against all modules
  .github/workflows/detekt.yml
Labels: Technical, Estimation - 1 (XS)

#4547 [RELEASE] 4.5.0-beta.1
  owncloudApp/build.gradle
  owncloudApp/src/main/java/com/owncloud/android/presentation/releasenotes/ReleaseNotesViewModel.kt
Labels: Approved by qa

#4548 [FIX] Removing local copy of non-previewable file leads to empty view
  CHANGELOG.md
  changelog/unreleased/4548
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
Labels: Approved by qa

#4549 [FEATURE REQUEST] Remove survey and chat from feedback
  CHANGELOG.md
  changelog/unreleased/4549
  owncloudApp/src/androidTest/java/com/owncloud/android/settings/more/SettingsMoreFragmentTest.kt
  owncloudApp/src/main/java/com/owncloud/android/extensions/ActivityExt.kt
  owncloudApp/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.kt
  owncloudApp/src/main/res/values-de-rDE/strings.xml
  owncloudApp/src/main/res/values-de/strings.xml
  owncloudApp/src/main/res/values-en-rGB/strings.xml
  owncloudApp/src/main/res/values-es/strings.xml
  owncloudApp/src/main/res/values-et-rEE/strings.xml
  owncloudApp/src/main/res/values-fi-rFI/strings.xml
  owncloudApp/src/main/res/values-ja-rJP/strings.xml
  owncloudApp/src/main/res/values-ko/strings.xml
  owncloudApp/src/main/res/values-pt-rBR/strings.xml
  owncloudApp/src/main/res/values-ru/strings.xml
  owncloudApp/src/main/res/values-sq/strings.xml
  owncloudApp/src/main/res/values-ug/strings.xml
  owncloudApp/src/main/res/values/strings.xml
Labels: Approved by qa

#4551 [TECHNICAL] Change Calens configuration in order not to block Github Actions
  .github/workflows/calens.yml
Labels: Technical
